spring:
  application:
    name: tms

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    # url: jdbc:mariadb://192.168.0.10:33306/tms
    url: jdbc:mariadb://172.19.0.2:3306/tms
    username: root
    password: 2846
    hikari: # DB Pool Size
      minimum-idle: 2
      maximum-pool-size: 5
  jpa:
    hibernate:
      #ddl option: none || validate || update | create | create-drop
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 23000
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
